### ISSUE TITLE
Incompatible with Anvil Crushing Recipes

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [RubixDev/fabric-rug#3]
This mod is incompatible with [Anvil Crushing Recipes](https://gitlab.com/supersaiyansubtlety/anvil_crushing_recipes). No crash report was generated, but I can provide the [latest.log](https://gist.github.com/DragonEggBedrockBreaking/bf094e8790263fede8f7fed563d39509).

**Comment by RubixDev** [comment]
Funnily enough it seems the incompatibility is not even because of the `anvilledIce` rules, but because of `strictShulkerShells`. I will try to rewrite that tomorrow.

**Comment by DragonEggBedrockBreaking** [comment]
> Funnily enough it seems the incompatibility is not even because of the `anvilledIce` rules, but because of `strictShulkerShells`. I will try to rewrite that tomorrow.

Well carpet extra adds a rule similar to `anvilledIce`, and they are compatible, so...

**Comment by supersaiyansubtlety** [comment]
(Dev of anvil crushing recipes)
I think the simplest thing would be to just use an [`IMixinConfigPlugin`](https://jenkins.liteloader.com/view/Other/job/Mixin/javadoc/org/spongepowered/asm/mixin/extensibility/IMixinConfigPlugin.html) to just disable your living entity mixin. 
I only suggest this as opposed to disabling anvil crushing recipe's mixin because `strictShulkerShells`'s behavior can be acheived with datapacks, albeit less conveniently and adjustably. 
I suppose another option would be to dynamically create a loottable for shulkers and force a reload whenever the setting changes, but not sure if that's worth the effort.

**Comment by RubixDev** [comment]
Will be fixed in the next Release.

**Comment by supersaiyansubtlety** [comment]
Thanks
