### ISSUE TITLE
silkTouchSpawners not saving mob type

### ISSUE THREAD

**Issue by ghost** [RubixDev/fabric-rug#30]
When I mine a spawner with silkTouchSpawners enabled, the dropped item is a default pig spawner, resetting the spawn time using a spawn egg and mining the block again results in the same behavior.

Minecraft 1.17.1
MultiMC 0.6.13-2519
Fabric Loader 0.11.6
Fabric API 0.40.0+1.17
Carpet 1.4.45
Rug 1.17.1-1.1.13

**Comment by RubixDev** [comment]
Sorry, but I am unable to reproduce that, it works for me. I right clicked a default pig spawner with a zombie spawn egg so it becomes a zombie spawner, switch to survival mode, mine the spawner with a silk touch netherite pickaxe and place it back down. After that it still is a zombie spawner

**Comment by SplendidAlakey** [comment]
I used to be able to reproduce it back then (hence the +1), but not anymore. I doubt it was a mod incompatibility as I'm still using all the same mods and the issue was reproducible with just Rug/Carpet alone if I recall. 

Maybe some changes in fabric 0.12+ fixed it ¯\\_(ツ)_/¯

ps. glad to see you back and in full force :)

**Comment by RubixDev** [comment]
> Maybe some changes in fabric 0.12+ fixed it ¯\(ツ)/¯

_We will never know_

> ps. glad to see you back and in full force :)

Yes, I am back, but probably not for long. I am quite busy with school (exam phase), christmas preperation and some other stuff currently, but I just had the urge to quickly update my mods to 1.18 and I couldn't just leave the open issues lying around...
