### ISSUE TITLE
Incompatible with Plan | Player Analytics

### ISSUE THREAD

**Issue by aisukuma** [RubixDev/fabric-rug#35]
No server crash, but it removes the /plan command from [Plan | Player Analytics](https://www.curseforge.com/minecraft/mc-mods/plan-player-analytics).

Here is a [gist of the latest.log](https://gist.github.com/aisukuma/542d9a25dd9866f1f09fc21d9f5f83e8) if you need it.

**Comment by RubixDev** [comment]
before I can investigate further, https://github.com/plan-player-analytics/Plan/issues/2969 will have to be addressed

**Comment by RubixDev** [comment]
Okay so after some tinkering I found out that the issue seems to be caused by the data reload during the first data load which is required for the custom crafting recipes. It was always ugly to have this reload there and already caused a problem with another mod, but so far I never found a way around it (see #41 and #17).
I will likely have another go and see where I get.

**Comment by RubixDev** [comment]
Well it works now, but I had to Inject into Carpet's `SettingsManager` class. Instead of loading all Minecraft resources twice during launch, instead the Carpet config is now read twice, but that is still much less demanding.

I will release v1.4.1 with this fix shortly
