### ISSUE TITLE
Incompatible with Dawn API

### ISSUE THREAD

**Issue by Neubulae** [RubixDev/fabric-rug#6]
https://hatebin.com/asqqgrqgqm

**Comment by RubixDev** [comment]
The incompatibility comes from `foodInstantHeal` and I think I already have an idea on how to rewrite it, so it's compatible with Dawn API. Otherwise I will just lower the priority of my redirect so `foodInstantHeal` then just wouldn't work with Dawn API installed. The soonest I can fix it will be tomorrow though.
