### ISSUE TITLE
Comment/Don't know what to write as a title

### ISSUE THREAD

**Issue by altrisi** [RubixDev/fabric-rug#9]
Hey! I've seen you've made a script to generate a readme from the rules, so even if it's too late already, I wanted to let you know that Carpet has a built-in generator for those readmes, which is included in the `/test dump [category]` command, available in development environments.

It is defined in [`SettingsManager#printAllRulesToLog(String category)`](https://github.com/gnembon/fabric-carpet/blob/8a1c9f2d0b451377fc5e4deea09472feaaa37db3/src/main/java/carpet/settings/SettingsManager.java#L485), and it does something quite similar to what your output looks like, except it doesn't have create an index (you can see sample output at the [Carpet wiki](https://github.com/gnembon/fabric-carpet/wiki/Current-Available-Settings) or the [Carpet extra readme](https://github.com/gnembon/carpet-extra/)).

**Comment by RubixDev** [comment]
Oh, thanks for the info, I didn't know about that, but I think I still prefer my Python script, because I'm still much more comfortable and familiar with Python than with Java and I can more easily customize it to my needs as you can see for example in [this commit](https://github.com/RubixDev/fabric-rug/commit/8381c1dd811e38d02ed6fc725645f1aedcae6f84). Thanks for the info anyways though.
